Update images with analytics button
ploomber/doc pull request #200
Opened 2024-04-22 12:09 UTC by neelasha23

2024-04-22 18:30 UTC, edublancas requested changes

2024-04-22 18:30 UTC, edublancas commented on doc/static/applications-form.png
the serverless functions, document processing, and scheduled functions are just an experiment.

open the platform on your browser, manually edit the HTML to remove those and take the screenshot again

2024-04-23 07:40 UTC, neelasha23 commented on doc/static/applications-form.png
[fixed](https://github.com/ploomber/doc/pull/200/commits/aa6188676a4288179f91ce140b73d547420585cf)

2024-04-23 14:09 UTC, edublancas approved these changes

2024-04-23 14:09 UTC, merged