Auth0 integration via CLI
ploomber/doc pull request #205
Opened 2024-04-25 19:28 UTC by bryannho

- Documents `ploomber-cloud templates auth0` on `userguide/password.md`

2024-04-25 21:35 UTC, edublancas requested changes

2024-04-25 21:35 UTC, edublancas commented on doc/static/password/auth0-credentials.png
the client secret is not `AUTH_SECRET`. I had the same doubt when working on this but based on the docs, it seems like `AUTH_SECRET` can be any string. I think we can even generate it ourselves:

```
In [2]: import secrets

In [3]: secrets.token_urlsafe()
Out[3]: 'xlFTwKeNh_8Up3TRbozpFtK8NZEX08sJ_72k7we4Fm4'

In [4]:

```

can you do some research on this?

2024-04-26 14:14 UTC, neelasha23 approved these changes
Looks fine overall

2024-04-26 15:33 UTC, merged

2024-04-26 15:34 UTC, edublancas commented
@bryannho I'm merging this because I want to add some extra details, please open another PR to address: https://github.com/ploomber/doc/issues/207