Add example for Streamlit app that uses PostgreSQL
ploomber/doc pull request #262
Opened 2024-08-01 20:52 UTC by stanleyo03

Link to app on Ploomber Cloud: https://restless-surf-9701.ploomberapp.io/
 
Closes #258

2024-08-02 01:08 UTC, bryannho requested changes
Basic function works well - one question.

When I enter a new data point in, I notice that I have to change one of the axes for the new point to be loaded on the chart and table (I assume because the frontend doesn't grab the new data until an axis is changed). This might be confusing since users expect to see it immediately without doing anything.

Can you add an automatic reload? You could have it reload after a delay (the postgres query should go through pretty fast) or worst case, add a refresh button to show the changes without changing any axes.

2024-08-02 15:46 UTC, bryannho commented
> This is not restarting for some reason:
> 
> <img width="1025" alt="Screenshot 2024-08-02 at 5 47 28 PM" src="https://github.com/user-attachments/assets/29c51b0a-9f82-4ad3-a1b0-cf91e43afd4a">
> 
> 
> 
> Can u please start the app and lmk @stanleyo03 

This is a bug on the backend. @stanleyo03 you probably need to delete this one and re deploy it as a new app

2024-08-02 15:47 UTC, stanleyo03 commented
@bryannho @neelasha23 Here is a new link: https://white-mode-0486.ploomberapp.io/

2024-08-02 16:24 UTC, bryannho reviewed
App looks good with the reload! One minor comment

2024-08-02 16:24 UTC, bryannho commented on examples/streamlit/postgres-connection/README.md
> +When deploying this app on Ploomber Cloud you need to set the `DB_URI` as a secret. Refer to the [documentation](https://docs.cloud.ploomber.io/en/latest/user-guide/secrets.html) to learn more.
Tell them directly to remove the `DB_URI` from the code here so that they don't expose their URI

2024-08-02 16:54 UTC, neelasha23 commented
In the left sidebar, please add a very brief description of the utility of the app and what happens when a user inputs a new point (what changes should they expect to see) @stanleyo03

2024-08-02 17:13 UTC, stanleyo03 commented
@bryannho @neelasha23 should be ready for merge

2024-08-02 17:43 UTC, bryannho approved these changes

2024-08-03 16:43 UTC, neelasha23 approved these changes

2024-08-03 16:43 UTC, merged